# Jidoteki Admin tasks
#
# user/group 998 = sftpadmin, 997 = admin, 50 = staff, 0 = root

- name: Create admin directory structure
  file: >
    state=directory
    path={{ prefix }}{{ item }}
    owner=0
    group=0
    mode=0755
  with_items:
    - "{{ admin_path }}"
    - "{{ admin_path }}/bin"
    - "{{ admin_path }}/tmp"
    - "{{ admin_path }}/lib"
    - "{{ admin_path }}/home/sftp"
  tags:
    - admin
    - lib

- name: Create admin home directories
  file: >
    state=directory
    path={{ prefix }}{{ item }}
    owner=997
    group=997
    mode=1750
    recurse=no
  with_items:
    - "{{ admin_path }}/home"
    - "{{ admin_path }}/home/.ssh"
  tags:
    - admin

- name: Create admin sftp uploads directory
  file: >
    state=directory
    path={{ prefix }}{{ item }}
    owner=998
    group=997
    mode=0770
    recurse=no
  with_items:
    - "{{ admin_path }}/home/sftp/uploads"
  tags:
    - admin

- name: Allow 'admin' to write to certain dirs
  file: >
    state=directory
    path={{ prefix }}{{ item }}
    owner=0
    group=997
    mode=1775
  with_items:
    - "{{ admin_path }}/log"
    - "{{ admin_path }}/etc"
  tags:
    - admin

- name: Add SSH admin management scripts
  template: >
    src={{ item }}.j2
    dest="{{ prefix }}{{ admin_path }}/bin/{{ item }}"
    owner=0
    group=0
    mode=0755
  with_items:
    - update_backup.sh
    - update_certs.sh
    - update_debug.sh
    - update_license.sh
    - update_logs.sh
    - update_replication.sh
    - update_services.sh
    - update_settings.sh
    - update_storage.sh
    - update_token.sh
    - update_vm.sh
  tags:
    - admin

- name: Add SSH admin wrapper script
  template: >
    src=wrapper.sh.j2
    dest="{{ prefix }}{{ admin_path }}/bin/wrapper.sh"
    owner=0
    group=997
    mode=0750
  tags:
    - admin

- name: Add SSH admin library scripts
  template: >
    src={{ item }}.j2
    dest="{{ prefix }}{{ admin_path }}/lib/{{ item }}"
    owner=0
    group=0
    mode=0644
  with_items:
    - tc-functions.l
  tags:
    - admin
    - lib

- name: Add SSH admin library deps
  git: >
    dest={{ prefix }}{{ admin_path }}/lib/{{ item.dir }}
    repo={{ item.repo }}
    version={{ item.ref }}
  with_items:
    - "{{ jidoteki_lib_deps }}"
  tags:
    - admin
    - lib
